/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mve_woden_Woden */

#ifndef _Included_org_mve_woden_Woden
#define _Included_org_mve_woden_Woden
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mve_woden_Woden
 * Method:    reset0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mve_woden_Woden_reset0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
